name: Monorepo Microservice CI/CD

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  build-a:
    name: Build Microservice A
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Build A
        run: |
          echo "🔧 Building microservice A..."
          python microservice-a/app.py
    paths:
      - 'microservice-a/**'

  build-b:
    name: Build Microservice B
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: Build B
        run: |
          echo "🔧 Building microservice B..."
          python microservice-b/app.py
    paths:
      - 'microservice-b/**'
